// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bare': string;
  'btn': string;
  'icon': string;
  'inline': string;
  'large': string;
  'medium': string;
  'small': string;
}
declare const cssExports: CssExports;
export = cssExports;
