// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'content': string;
  'footer': string;
  'header': string;
  'information': string;
  'logo': string;
  'privacy': string;
}
declare const cssExports: CssExports;
export = cssExports;
