// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'left': string;
  'right': string;
  'row': string;
}
declare const cssExports: CssExports;
export = cssExports;
