// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mainImage': string;
  'photoRow': string;
  'tile': string;
  'tileInner': string;
}
declare const cssExports: CssExports;
export = cssExports;
