// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'form': string;
  'interactive': string;
  'speech': string;
}
declare const cssExports: CssExports;
export = cssExports;
