// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'large': string;
  'medium': string;
  'small': string;
  'wrap': string;
}
declare const cssExports: CssExports;
export = cssExports;
