// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inner': string;
  'single-message': string;
}
declare const cssExports: CssExports;
export = cssExports;
