// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'highlight': string;
  'speech': string;
}
declare const cssExports: CssExports;
export = cssExports;
