// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SPIN': string;
  'animated': string;
  'message': string;
}
declare const cssExports: CssExports;
export = cssExports;
