// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hasHighlighted': string;
  'highlighted': string;
  'image': string;
  'list': string;
  'selected': string;
}
declare const cssExports: CssExports;
export = cssExports;
