// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'image': string;
  'list': string;
  'modal': string;
  'modalContent': string;
  'overlay': string;
}
declare const cssExports: CssExports;
export = cssExports;
