// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'toast': string;
  'wrapper': string;
}
declare const cssExports: CssExports;
export = cssExports;
